name: magician
favicon: null
layout_spectrum: 0.49506
typography_spectrum: 0.73671
title: exploring the intersection of technology and magic
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#454f57'
    - '#6b99b5'
    - '#e62a1d'
    - '#060606'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
